apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
      - name: ganache
        image: your-dockerhub-username/ganache:latest
        ports:
        - containerPort: 8545
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ganache-service
spec:
  selector:
    app: ganache
  ports:
  - protocol: TCP
    port: 8545
    targetPort: 8545
  type: ClusterIP
